### ISSUE TITLE
BUG: RecursionError on init

### ISSUE THREAD

**Issue by Khai2002** [rahulanand1103/rag-citation#1]
cite_item = CiteItem(answer=answer, context=context)
inference = Inference()

Both of them make this error:
RecursionError: maximum recursion depth exceeded while calling a Python object

This happens in the example file as well as your test file.

**Comment by rahulanand1103** [comment]
Could you please tell me which version of Python you are using?

**Comment by Khai2002** [comment]
I'm using python 3.12. And thank you for responding so quickly!

**Comment by rahulanand1103** [comment]
I try to recreate the error but cannot do it.
please paste the complete error.

**Comment by Khai2002** [comment]
Btw, I have some other packages installed in my project venv, but I doubt they would be a problem.

Here you go, full error:

RecursionError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 from rag_citation import CiteItem, Inference
      3 inference = Inference()

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\rag_citation\__init__.py:2
      1 from rag_citation.cite_item import CiteItem
----> 2 from rag_citation.inference import Inference
      4 __all__ = ["CiteItem", "Inference"]

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\rag_citation\inference.py:7
      4 from typing import List, Dict
      5 from tqdm import tqdm
----> 7 from rag_citation.focus_word import FocusWordDataType, FocusWord
      8 from rag_citation.pair import GeneratePair
      9 from rag_citation.score import Score

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\rag_citation\focus_word\__init__.py:1
----> 1 from rag_citation.focus_word.focus_word import FocusWord
      2 from rag_citation.focus_word.schema import FocusWordDataType
      4 __all__ = ["FocusWord", "FocusWordDataType"]

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\rag_citation\focus_word\focus_word.py:3
      1 import spacy
      2 from rag_citation.focus_word.schema import FocusWordDataType
----> 3 from rag_citation.base_model import SpacyBaseModel
      6 class FocusWord(SpacyBaseModel):
      7     """
      8     Class for extracting focus words (entities and nouns) from a text answer using SpaCy.
      9 
   (...)
     17                                      Defaults to "sm".
     18     """

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\rag_citation\base_model\__init__.py:3
      1 from rag_citation.base_model.base import BaseEmbeddingModel
      2 from rag_citation.base_model.spacy_model import SpacyBaseModel
----> 3 from rag_citation.base_model.embedding_model import EmbeddingModel
      6 __all__ = ["SpacyBaseModel", "BaseEmbeddingModel", "EmbeddingModel"]

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\rag_citation\base_model\embedding_model.py:1
----> 1 from sentence_transformers import SentenceTransformer
      2 from rag_citation.base_model.base import BaseEmbeddingModel
      5 class EmbeddingModel(BaseEmbeddingModel):

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sentence_transformers\__init__.py:7
      4 import importlib
      5 import os
----> 7 from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
      8 from sentence_transformers.datasets import ParallelSentencesDataset, SentencesDataset
      9 from sentence_transformers.LoggingHandler import LoggingHandler

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sentence_transformers\cross_encoder\__init__.py:1
----> 1 from .CrossEncoder import CrossEncoder
      3 __all__ = ["CrossEncoder"]

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:16
     13 from transformers.tokenization_utils_base import BatchEncoding
     14 from transformers.utils import PushToHubMixin
---> 16 from sentence_transformers.evaluation.SentenceEvaluator import SentenceEvaluator
     17 from sentence_transformers.readers import InputExample
     18 from sentence_transformers.SentenceTransformer import SentenceTransformer

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sentence_transformers\evaluation\__init__.py:1
----> 1 from .BinaryClassificationEvaluator import BinaryClassificationEvaluator
      2 from .EmbeddingSimilarityEvaluator import EmbeddingSimilarityEvaluator
      3 from .InformationRetrievalEvaluator import InformationRetrievalEvaluator

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sentence_transformers\evaluation\BinaryClassificationEvaluator.py:8
      5 from typing import TYPE_CHECKING, Dict, List, Optional
      7 import numpy as np
----> 8 from sklearn.metrics import average_precision_score
      9 from sklearn.metrics.pairwise import paired_cosine_distances, paired_euclidean_distances, paired_manhattan_distances
     11 from sentence_transformers.evaluation.SentenceEvaluator import SentenceEvaluator

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\__init__.py:84
     70     # We are not importing the rest of scikit-learn during the build
     71     # process, as it may not be compiled yet
     72 else:
   (...)
     78     # later is linked to the OpenMP runtime to make it possible to introspect
     79     # it and importing it first would fail if the OpenMP dll cannot be found.
     80     from . import (
     81         __check_build,  # noqa: F401
     82         _distributor_init,  # noqa: F401
     83     )
---> 84     from .base import clone
     85     from .utils._show_versions import show_versions
     87     __all__ = [
     88         "calibration",
     89         "cluster",
   (...)
    130         "show_versions",
    131     ]

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\base.py:19
     17 from ._config import config_context, get_config
     18 from .exceptions import InconsistentVersionWarning
---> 19 from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
     20 from .utils._metadata_requests import _MetadataRequester, _routing_enabled
     21 from .utils._param_validation import validate_parameter_constraints

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\utils\__init__.py:11
      9 from . import _joblib, metadata_routing
     10 from ._bunch import Bunch
---> 11 from ._chunking import gen_batches, gen_even_slices
     12 from ._estimator_html_repr import estimator_html_repr
     14 # Make _safe_indexing importable from here for backward compat as this particular
     15 # helper is considered semi-private and typically very useful for third-party
     16 # libraries that want to comply with scikit-learn's estimator API. In particular,
     17 # _safe_indexing was included in our public API documentation despite the leading
     18 # `_` in its name.

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\utils\_chunking.py:8
      5 import numpy as np
      7 from .._config import get_config
----> 8 from ._param_validation import Interval, validate_params
     11 def chunk_generator(gen, chunksize):
     12     """Chunk generator, ``gen`` into lists of length ``chunksize``. The last
     13     chunk may have a length less than ``chunksize``."""

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\utils\_param_validation.py:14
     11 from scipy.sparse import csr_matrix, issparse
     13 from .._config import config_context, get_config
---> 14 from .validation import _is_arraylike_not_scalar
     17 class InvalidParameterError(ValueError, TypeError):
     18     """Custom exception to be raised when the parameter of a class/method/function
     19     does not have a valid type or value.
     20     """

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\utils\validation.py:26
     24 from .. import get_config as _get_config
     25 from ..exceptions import DataConversionWarning, NotFittedError, PositiveSpectrumWarning
---> 26 from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
     27 from ..utils.fixes import ComplexWarning, _preserve_dia_indices_dtype
     28 from ._isfinite import FiniteStatus, cy_isfinite

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\utils\_array_api.py:11
      8 import scipy.special as special
     10 from .._config import get_config
---> 11 from .fixes import parse_version
     13 _NUMPY_NAMESPACE_NAMES = {"numpy", "array_api_compat.numpy"}
     16 def yield_namespaces(include_numpy_namespaces=True):

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\sklearn\utils\fixes.py:21
     19 import scipy
     20 import scipy.sparse.linalg
---> 21 import scipy.stats
     23 try:
     24     import pandas as pd

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\stats\__init__.py:610
      1 """
      2 .. _statsrefmanual:
      3 
   (...)
    605 
    606 """  # noqa: E501
    608 from ._warnings_errors import (ConstantInputWarning, NearConstantInputWarning,
    609                                DegenerateDataWarning, FitError)
--> 610 from ._stats_py import *
    611 from ._variation import variation
    612 from .distributions import *

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\stats\_stats_py.py:49
     46 # Import unused here but needs to stay until end of deprecation periode
     47 # See https://github.com/scipy/scipy/issues/15765#issuecomment-1875564522
     48 from scipy import linalg  # noqa: F401
---> 49 from . import distributions
     50 from . import _mstats_basic as mstats_basic
     52 from ._stats_mstats_common import _find_repeats, theilslopes, siegelslopes

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\stats\distributions.py:10
      1 #
      2 # Author:  Travis Oliphant  2002-2011 with contributions from
      3 #          SciPy Developers 2004-2011
   (...)
      6 #       instead of `git blame -Lxxx,+x`.
      7 #
      8 from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)  # noqa: F401
---> 10 from . import _continuous_distns
     11 from . import _discrete_distns
     13 from ._continuous_distns import *  # noqa: F403

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\stats\_continuous_distns.py:12
     10 import numpy as np
     11 from numpy.polynomial import Polynomial
---> 12 from scipy.interpolate import BSpline
     13 from scipy._lib.doccer import (extend_notes_in_docstring,
     14                                replace_notes_in_docstring,
     15                                inherit_docstring_from)
     16 from scipy._lib._ccallback import LowLevelCallable

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\interpolate\__init__.py:167
      1 """
      2 ========================================
      3 Interpolation (:mod:`scipy.interpolate`)
   (...)
    165 (should not be used in new code).
    166 """
--> 167 from ._interpolate import *
    168 from ._fitpack_py import *
    170 # New interface to fitpack library:

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\interpolate\_interpolate.py:12
      9 from scipy._lib._util import copy_if_needed
     10 from scipy.special import comb
---> 12 from . import _fitpack_py
     13 from ._polyint import _Interpolator1D
     14 from . import _ppoly

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\interpolate\_fitpack_py.py:8
      5 import numpy as np
      7 # These are in the API for fitpack even if not used in fitpack.py itself.
----> 8 from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
      9 from . import _fitpack_impl as _impl
     10 from ._bsplines import BSpline

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\scipy\interpolate\_fitpack_impl.py:103
     52 _iermess = {
     53     0: ["The spline has a residual sum of squares fp such that "
     54         "abs(fp-s)/s<=0.001", None],
   (...)
     68     'unknown': ["An error occurred", TypeError]
     69 }
     71 _iermess2 = {
     72     0: ["The spline has a residual sum of squares fp such that "
     73         "abs(fp-s)/s<=0.001", None],
   (...)
     99     'unknown': ["An error occurred", TypeError]
    100 }
    102 _parcur_cache = {'t': array([], float), 'wrk': array([], float),
--> 103                  'iwrk': array([], dfitpack_int), 'u': array([], float),
    104                  'ub': 0, 'ue': 1}
    107 def splprep(x, w=None, u=None, ub=None, ue=None, k=3, task=0, s=None, t=None,
    108             full_output=0, nest=None, per=0, quiet=1):
    109     # see the docstring of `_fitpack_py/splprep`
    110     if task <= 0:

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:46, in __repr__(dtype)
     45 def __repr__(dtype):
---> 46     arg_str = _construction_repr(dtype, include_align=False)
     47     if dtype.isalignedstruct:
     48         arg_str = arg_str + ", align=True"

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:100, in _construction_repr(dtype, include_align, short)
     98     return _subarray_str(dtype)
     99 else:
--> 100     return _scalar_str(dtype, short=short)

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:143, in _scalar_str(dtype, short)
    140 elif dtype.type == np.timedelta64:
    141     return "'%sm8%s'" % (byteorder, _datetime_metadata_str(dtype))
--> 143 elif np.issubdtype(dtype, np.number):
    144     # Short repr with endianness, like '<f8'
    145     if short or dtype.byteorder not in ('=', '|'):
    146         return "'%s%c%d'" % (byteorder, dtype.kind, dtype.itemsize)

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\numerictypes.py:417, in issubdtype(arg1, arg2)
    359 r"""
    360 Returns True if first argument is a typecode lower/equal in type hierarchy.
    361 
   (...)
    414 
    415 """
    416 if not issubclass_(arg1, generic):
--> 417     arg1 = dtype(arg1).type
    418 if not issubclass_(arg2, generic):
    419     arg2 = dtype(arg2).type

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:46, in __repr__(dtype)
     45 def __repr__(dtype):
---> 46     arg_str = _construction_repr(dtype, include_align=False)
     47     if dtype.isalignedstruct:
     48         arg_str = arg_str + ", align=True"

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:100, in _construction_repr(dtype, include_align, short)
     98     return _subarray_str(dtype)
     99 else:
--> 100     return _scalar_str(dtype, short=short)

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:143, in _scalar_str(dtype, short)
    140 elif dtype.type == np.timedelta64:
    141     return "'%sm8%s'" % (byteorder, _datetime_metadata_str(dtype))
--> 143 elif np.issubdtype(dtype, np.number):
    144     # Short repr with endianness, like '<f8'
    145     if short or dtype.byteorder not in ('=', '|'):
    146         return "'%s%c%d'" % (byteorder, dtype.kind, dtype.itemsize)

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\numerictypes.py:417, in issubdtype(arg1, arg2)
    359 r"""
    360 Returns True if first argument is a typecode lower/equal in type hierarchy.
    361 
   (...)
    414 
    415 """
    416 if not issubclass_(arg1, generic):
--> 417     arg1 = dtype(arg1).type
    418 if not issubclass_(arg2, generic):
    419     arg2 = dtype(arg2).type

    [... skipping similar frames: __repr__ at line 46 (329 times), _construction_repr at line 100 (329 times), _scalar_str at line 143 (328 times), issubdtype at line 417 (328 times)]

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:143, in _scalar_str(dtype, short)
    140 elif dtype.type == np.timedelta64:
    141     return "'%sm8%s'" % (byteorder, _datetime_metadata_str(dtype))
--> 143 elif np.issubdtype(dtype, np.number):
    144     # Short repr with endianness, like '<f8'
    145     if short or dtype.byteorder not in ('=', '|'):
    146         return "'%s%c%d'" % (byteorder, dtype.kind, dtype.itemsize)

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\numerictypes.py:417, in issubdtype(arg1, arg2)
    359 r"""
    360 Returns True if first argument is a typecode lower/equal in type hierarchy.
    361 
   (...)
    414 
    415 """
    416 if not issubclass_(arg1, generic):
--> 417     arg1 = dtype(arg1).type
    418 if not issubclass_(arg2, generic):
    419     arg2 = dtype(arg2).type

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:46, in __repr__(dtype)
     45 def __repr__(dtype):
---> 46     arg_str = _construction_repr(dtype, include_align=False)
     47     if dtype.isalignedstruct:
     48         arg_str = arg_str + ", align=True"

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:100, in _construction_repr(dtype, include_align, short)
     98     return _subarray_str(dtype)
     99 else:
--> 100     return _scalar_str(dtype, short=short)

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:104, in _scalar_str(dtype, short)
    103 def _scalar_str(dtype, short):
--> 104     byteorder = _byte_order_str(dtype)
    106     if dtype.type == np.bool_:
    107         if short:

File ~\PycharmProjects\R3-citation\.venv\Lib\site-packages\numpy\core\_dtype.py:163, in _byte_order_str(dtype)
    161 """ Normalize byteorder to '<' or '>' """
    162 # hack to obtain the native and swapped byte order characters
--> 163 swapped = np.dtype(int).newbyteorder('S')
    164 native = swapped.newbyteorder('S')
    166 byteorder = dtype.byteorder

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by rahulanand1103** [comment]
Could you please create a new environment and install rag_citation? I suspect there’s a conflict between sklearn, numpy, and rag_citation.

**Comment by Khai2002** [comment]
I tried to clone the git, I gave me a different error during init:
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by rahulanand1103** [comment]
use this command to download spacy model
`python -m spacy download en_core_web_sm`
or 
`python3 -m spacy download en_core_web_sm`

for your  reference:
https://spacy.io/usage/models

**Comment by Khai2002** [comment]
It works for me now. 

I'll try to figure out what caused the issue. I'll update it here so don't close it just yet.

**Comment by rahulanand1103** [comment]
okay
Thanks a lot 🙏
